source 'https://github.com/CocoaPods/Specs.git'
#source 'git@gitee.com:wangjingming_iOS/Specs.git'
platform :ios, '13.0'

target 'TestRX' do
    inhibit_all_warnings!
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
    
  # Rx
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  

end
